# 数据源
spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password:
# 初始化脚本
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

#管理界面设置 http://localhost:8080/h2-console
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
